name: Build and Deploy
on:
  push:
    branches:
      - master

env:
  FB_PROJECT: jarvis-dev-268314
  FB_HOSTING_WONKA: hosting:wonka-dev
  FB_HOSTING_WONKA_STG: hosting:wonka-stg
  FB_HOSTING_SLUGWORTH: hosting:slugworth-dev
  FB_HOSTING_SLUGWORTH_STG: hosting:slugworth-stg

jobs:
  build-ts-web:
    name: Build TypeScript Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - name: Install Web Project
        run: yarn install
      - name: Build TypeScript
        run: |
          yarn web-ts build

  build-deploy-wonka-web:
    name: Deploy Web Dev - wonka
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - name: Setup Env Variables
        run: |
          mv ./packages/web/.env-wonka ./packages/web/.env
      - name: Install Web Project
        run: yarn install
      - name: Build
        run: |
          yarn web build
      - name: Install FB Tools
        run: npm install -g firebase-tools
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_KEY}}
        run: |
          firebase use $FB_PROJECT --token $FIREBASE_TOKEN
          firebase deploy --only $FB_HOSTING_WONKA --token $FIREBASE_TOKEN -m "CI deploy commit ${GITHUB_SHA::8}" --non-interactive

  build-deploy-wonka-web-stg:
    name: Deploy Web Staging - wonka
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - name: Setup Env Variables
        run: |
          mv ./packages/web/.env-wonka-stg ./packages/web/.env
      - name: Install Web Project
        run: yarn install
      - name: Build
        run: |
          yarn web build
      - name: Install FB Tools
        run: npm install -g firebase-tools
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_KEY}}
        run: |
          firebase use $FB_PROJECT --token $FIREBASE_TOKEN
          firebase deploy --only $FB_HOSTING_WONKA_STG --token $FIREBASE_TOKEN -m "CI deploy commit ${GITHUB_SHA::8}" --non-interactive

  build-deploy-slugworth-web:
    name: Deploy Web Dev - slugworth
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - name: Setup Env Variables
        run: |
          mv ./packages/web/.env-slugworth ./packages/web/.env
      - name: Install Web Project
        run: yarn install
      - name: Build
        run: |
          yarn web build
      - name: Install FB Tools
        run: npm install -g firebase-tools
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_KEY}}
        run: |
          firebase use $FB_PROJECT --token $FIREBASE_TOKEN
          firebase deploy --only $FB_HOSTING_SLUGWORTH --token $FIREBASE_TOKEN -m "CI deploy commit ${GITHUB_SHA::8}" --non-interactive
  build-deploy-slugworth-web-stg:
    name: Deploy Web Stg - slugworth
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - name: Setup Env Variables
        run: |
          mv ./packages/web/.env-slugworth-stg ./packages/web/.env
      - name: Install Web Project
        run: yarn install
      - name: Build
        run: |
          yarn web build
      - name: Install FB Tools
        run: npm install -g firebase-tools
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEV_KEY}}
        run: |
          firebase use $FB_PROJECT --token $FIREBASE_TOKEN
          firebase deploy --only $FB_HOSTING_SLUGWORTH_STG --token $FIREBASE_TOKEN -m "CI deploy commit ${GITHUB_SHA::8}" --non-interactive
